debug: true
server:
  port: 3010
  applications:
    sms_api_key: 6SCzcO1CzznAffqHDTdfr4b2atB+d1HE22rGGWa5kWM=
    sms_client_id: e038f2d0-1e34-46ef-8513-92a2ee011a57
    sms_base_url: https://api.mylogin.co.in/api/v2/
    sms_sender_id: BWBHSC 
    
logging:
  file:
    name: logs/applications.log
     
